const apiUrl = `http://localhost/api/`;

export const apiEndpoints = {
    endpointPrijava: `${apiUrl}prijava`,
    endpointRegistracija: `${apiUrl}registracijaKorisnika`,
    endpointDodajKorisnika: `${apiUrl}dodajKorisnika`,
    endpointMojProfil: `${apiUrl}mojProfil`,
    endpointSviKorisnici: `${apiUrl}sviKorisnici`,
    endpointSviZaposleni: `${apiUrl}sviZaposleni`,
    endpointAzurirajPodatke: `${apiUrl}azurirajPodatke`,
    endpointIzmeniKorisnika: `${apiUrl}izmeniKorisnika`,
    endpointZakazaniTermini: `${apiUrl}zakazaniTermini`,
    endpointSveUsluge: `${apiUrl}sveUsluge`,
    endpointMojeUsluge: `${apiUrl}mojeUsluge`,
    endpointPodaciOUsluzi: `${apiUrl}podaciOUsluzi`,
    endpointZakazaniTermini: `${apiUrl}zakazaniTermini`,
    endpointKorisniciSlobodniTermini: `${apiUrl}korisniciSlobodniTermini`,
    endpointKorisniciZakazaniTermini: `${apiUrl}korisniciZakazaniTermini`,
    endpointZakaziTermin: `${apiUrl}zakaziTermin`,
    endpointOtkaziTermin: `${apiUrl}otkaziTermin`,
    endpointObrisiKorisnika: `${apiUrl}obrisiKorisnika`,
    endpointZaposleniSlobodniTermini: `${apiUrl}zaposleniSlobodniTermini`,
    endpointObrisiTermin: `${apiUrl}obrisiTermin`,
    endpointDodajTermin: `${apiUrl}dodajTermin`,
}